events { }

http {
    upstream node_backend {
        server backend-node:5000;
    }

    upstream spring_backend {
        server backend-spring:8080;
    }

    server {
        listen 80;

        location /api/node/ {
            proxy_pass http://node_backend/;
        }

        location /api/spring/ {
            proxy_pass http://spring_backend/;
        }

        location / {
            proxy_pass http://frontend-react:3000;
        }
    }
}
